-- 06/07/2021
ALTER TABLE com_maeproveedor
    ADD COLUMN  PRO_FECHACREADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECINIACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECCESACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECREIACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECACTUALIZACION DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_CLASECONTRIBUYENTE VARCHAR(100);
