ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECHACREADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECINIACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECCESACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECREIACTIVIDADES DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_FECACTUALIZACION DATE;

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_CLASECONTRIBUYENTE VARCHAR(100);

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_ESTADO VARCHAR(1) DEFAULT '1';

ALTER TABLE com_maeproveedor
    ADD COLUMN PRO_GMAPS VARCHAR(600) DEFAULT NULL;

ALTER TABLE ven_maecliente
    ADD COLUMN CLI_FECHACREADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

create table SEG_MAEUBIGEOGRAFICA
(
    UBIGEO_CODIGO VARCHAR (25) not null,
    UBIGEO_NOMBRE VARCHAR (100) not null,
    UBIGEO_NIVEL SMALLINT (10) not null,
    CAPITAL VARCHAR (1) default 0 not null,
    COM_CODIGO VARCHAR (10) not null
)