import { DataTypes, Op } from 'sequelize';
import db from '../db/connection';

const Cliente = db.define('ven_maecliente', {
    CLI_CODIGO: { type: DataTypes.STRING(20), primaryKey: true, allowNull: false, },
    GRU_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    VEN_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_NOMBREC: { type: DataTypes.STRING(200), allowNull: true, defaultValue: null, },
    CLI_NOMBRE: { type: DataTypes.STRING(200), allowNull: false, },
    CLI_TIPOIDE: { type: DataTypes.STRING(2), allowNull: true, defaultValue: null, },
    CLI_RUCIDE: { type: DataTypes.STRING(15), unique: true, allowNull: false, },
    CLI_DIRECCION1: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_DIRECCION2: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_CODPOSTAL: { type: DataTypes.STRING(15), allowNull: true, defaultValue: null, },
    CLI_TELEFONO1: { type: DataTypes.STRING(15), allowNull: true, defaultValue: null, },
    CLI_TELEFONO2: { type: DataTypes.STRING(15), allowNull: true, defaultValue: null, },
    CLI_FAX: { type: DataTypes.STRING(15), allowNull: true, defaultValue: null, },
    CLI_CORREO: { type: DataTypes.STRING(150), allowNull: true, defaultValue: null, },
    CLI_CONTACTO: { type: DataTypes.STRING(60), allowNull: true, defaultValue: null, },
    CLI_FECING: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_LIMCREDIT: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    CLI_DIACREDIT: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_DESCUENTO: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    CLI_IVA: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_CONTRIBUYENTE: { type: DataTypes.STRING(2), allowNull: true, defaultValue: null, },
    CLI_LISTA: { type: DataTypes.STRING(20), allowNull: true, defaultValue: 'A', },
    CON_CODIGO1: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CON_CODIGO2: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CLI_ZONA: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_OBSERVACION: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_SALDO: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    NOM_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    DEP_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_TIPO: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CLI_PROVINCIA: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CIU_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    TCR_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_TRFIVA: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CLI_TRFRETENCION: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CBR_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_ESTADO: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    ENCFFA_CODIGO: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_LINNEG: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CLI_PORCEDESCUENTO: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_VALORRECARGO: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    CLI_PORCERECARGO: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_FECHAULTPAG: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_CODSEGURIDAD: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_FLAG: { type: DataTypes.INTEGER, allowNull: false, },
    CEN_CODIGO: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CLI_LOCAL: { type: DataTypes.STRING(150), allowNull: true, defaultValue: null, },
    CLI_FECHANACIMIENTO: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_SEXO: { type: DataTypes.STRING(2), allowNull: true, defaultValue: null, },
    CLI_CARGO: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_DIACHPOS: { type: DataTypes.INTEGER, allowNull: true, defaultValue: 0, },
    CLI_UNIFICA: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_EXCLUYE: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_DESCUENTOLIM: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    CON_CODIGO3: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    COM_CODIGO: { type: DataTypes.STRING(2), primaryKey: true, allowNull: false, },
    GRU_TIPO: { type: DataTypes.STRING(3), allowNull: false, },
    BANCLI_CODIGO: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CLI_NROCUENTA: { type: DataTypes.STRING(20), allowNull: true, defaultValue: null, },
    CLI_LIDER: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_JEFE: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_TARDSC: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_PRECIOAC20: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    CLI_PRECIORC250: { type: DataTypes.FLOAT, allowNull: true, defaultValue: null, },
    USUARIO: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_INACTIVO: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_NUMEROCUOTAS: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_INCREMENTO: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_FACTURAELECT: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_CORREO2: { type: DataTypes.STRING(150), allowNull: true, defaultValue: null, },
    CLI_PARTEREL: { type: DataTypes.STRING(2), allowNull: true, defaultValue: null, },
    CLI_CLAVSACIANEX: { type: DataTypes.STRING(60), allowNull: true, defaultValue: null, },
    CLI_FORMAPAGO_CODSRI: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_TIPODEN: { type: DataTypes.STRING(20), allowNull: true, defaultValue: null, },
    CLI_INSTRUCCION: { type: DataTypes.STRING(50), allowNull: true, defaultValue: null, },
    CLI_TIPOSANGRE: { type: DataTypes.STRING(5), allowNull: true, defaultValue: null, },
    CLI_TALLA: { type: DataTypes.STRING(3), allowNull: true, defaultValue: null, },
    CLI_CATEGORIA: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_NOMALUMNO: { type: DataTypes.STRING(150), allowNull: true, defaultValue: null, },
    CLI_APEALUMNO: { type: DataTypes.STRING(150), allowNull: true, defaultValue: null, },
    CLI_LICENCIA: { type: DataTypes.STRING(50), allowNull: true, defaultValue: null, },
    CLI_SUJETO: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CAN_CODIGO: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    PARR_CODIGO: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_ESTCIV: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_ORGING: { type: DataTypes.STRING(10), allowNull: true, defaultValue: null, },
    CLI_GMAPS: { type: DataTypes.STRING(600), allowNull: true, defaultValue: null, },
    CLI_ACTIVIDAD: { type: DataTypes.STRING(600), allowNull: true, defaultValue: null, },
    CLI_CLASECONTRIBUYENTE: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_TIPOCONTRIBUYENTE: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_FECINIACTIVIDADES: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_FECCESACTIVIDADES: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_FECREIACTIVIDADES: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_FECACTUALIZACION: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_CATMIPYMES: { type: DataTypes.STRING(100), allowNull: true, defaultValue: null, },
    CLI_FECHACREADO: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW, },
    CLI_FECHACONSULTA: { type: DataTypes.DATE, allowNull: true, defaultValue: null, },
    CLI_BASEIVA: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CLI_BASECERO: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CLI_BASENOBJET: { type: DataTypes.STRING(35), allowNull: true, defaultValue: null, },
    CLI_CIUDAD: { type: DataTypes.STRING(25), allowNull: true, defaultValue: null, },
    CLI_CLAVESRI: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEIESSEMPLEADO: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEIESSEMPLEADOR: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEIESSDOMESTICA: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEMRLCONTRATOS: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEMRLFORMULARIOS: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_USUARIOSUPER: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVESUPER: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEMUNICIPIO: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_USUARIOSERCOP: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVESERCOP: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEQUIPUX: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_CLAVEUAFE: { type: DataTypes.STRING(40), allowNull: true, defaultValue: null, },
    CLI_REGION: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null, },
    CLI_CEDULA: { type: DataTypes.STRING(20), allowNull: true, defaultValue: null, },
    CLI_REPRESENTANTELEGAL: { type: DataTypes.STRING(200), allowNull: true, defaultValue: null, },
    CLI_CATEGORIARUC: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_DIGITO: { type: DataTypes.STRING(11), allowNull: true, defaultValue: null, },
    CLI_VENCE: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null, },
    CLI_MICROEMPRESA: { type: DataTypes.STRING(80), allowNull: true, defaultValue: null, },
    CLI_CONTRIESPECIAL: { type: DataTypes.STRING(80), allowNull: true, defaultValue: null, },
    CLI_EMPRESAFANTAS: { type: DataTypes.STRING(80), allowNull: true, defaultValue: null, },
    CLI_AGENRETENCION: { type: DataTypes.STRING(80), allowNull: true, defaultValue: null, },
    CLI_TIPOCLIENTE: { type: DataTypes.INTEGER, allowNull: false, },
    CLI_NUMEROAFILIADOS: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    CLI_TIPOJURIDICA: { type: DataTypes.INTEGER, allowNull: true, defaultValue: null },
    CLI_SUPERAMONTOACTIVOS_DEC_PATR: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null },
    CLI_AFILIADOIESS: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null },
    CLI_REGIMENRUC: { type: DataTypes.STRING(15), allowNull: true, defaultValue: null },
    CLI_INMUEBLE_REG_MUNI: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null },
    CLI_CONTRATARAUDITORIASUPER: { type: DataTypes.STRING(1), allowNull: true, defaultValue: null },
}, {
    timestamps: false,
    freezeTableName: true
});

export default Cliente;